spring:
  profiles:
    active: dev 
---
eureka:
  instance:
    instance-id: dept-8001.com
  client:
    serviceUrl: 
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka/
spring:
  application:
    name: micro-cloud-dept-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource  # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/dept8001       # 数据库连接地址
    username: root                        # 数据库用户名
    password: mysqladmin                      # 数据库连接密码
    dbcp2:                                    # 进行数据库连接池的配置
      min-idle: 1                             # 数据库连接池的最小维持连接数    
      initial-size: 1                           # 初始化提供的连接数
      max-total: 1                              # 最大的连接数
      max-wait-millis: 3000                   # 等待连接获取的最大超时时间
  profiles: dev 
server: 
  port: 8001

  
  